version: "3.8"

services:
    app:
        image: mcr.microsoft.com/devcontainers/typescript-node:24-bookworm
        volumes:
            - ..:/workspace/k8s-controller:cached
            - k3s-kubeconfig:/tmp/k3s
            - /var/run/docker.sock:/var/run/docker.sock
        working_dir: /workspace/k8s-controller
        command: sleep infinity
        depends_on:
            - valkey
            - iobroker
            - k3s-master
        environment:
            - IOB_K8S_REDIS_HOST=valkey
            - IOB_K8S_REDIS_PORT=6379
            - IOB_K8S_REDIS_PASSWORD=iobroker
            - IOB_K8S_REDIS_DB=0
            - KUBECONFIG=/tmp/k3s/kubeconfig.devcontainer

    valkey:
        image: valkey/valkey:8-alpine
        restart: unless-stopped
        command: valkey-server --appendonly yes --requirepass iobroker
        volumes:
            - valkey-data:/data
        ports:
            - "6379:6379"
        environment:
            - VALKEY_PASSWORD=iobroker

    iobroker:
        image: iobroker/iobroker:latest
        restart: unless-stopped
        hostname: iobroker
        ports:
            - "8081:8081"
            - "8082:8082"
            - "8083:8083"
            - "8084:8084"
        volumes:
            - iobroker-data:/opt/iobroker
        environment:
            - TZ=Europe/Zurich
            - IOB_MULTIHOST=master
            - IOB_OBJECTSDB_TYPE=redis
            - IOB_OBJECTSDB_HOST=valkey
            - IOB_OBJECTSDB_PORT=6379
            - IOB_OBJECTSDB_PASS=iobroker
            - IOB_STATESDB_TYPE=redis
            - IOB_STATESDB_HOST=valkey
            - IOB_STATESDB_PORT=6379
            - IOB_STATESDB_PASS=iobroker
        depends_on:
            - valkey

    k3s-master:
        image: rancher/k3s:v1.32.5-k3s1
        command: server --write-kubeconfig-mode=644
        hostname: k3s-master
        tmpfs:
            - /run
            - /var/run
        ulimits:
            nproc: 65535
            nofile:
                soft: 65535
                hard: 65535
        privileged: true
        restart: unless-stopped
        environment:
            - K3S_TOKEN=k8s-controller-token
            - K3S_KUBECONFIG_OUTPUT=/tmp/k3s/kubeconfig
            - K3S_KUBECONFIG_MODE=666
        volumes:
            - k3s-server:/var/lib/rancher/k3s
            - k3s-kubeconfig:/tmp/k3s
        ports:
            - "7443:6443"
            - "80:80"
            - "443:443"

volumes:
    valkey-data:
    iobroker-data:
    k3s-server:
    k3s-kubeconfig:
