apiVersion: batch/v1
kind: Job
metadata:
  name: "install-{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "install-{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: setup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "setup"
        env:
          - name: IOB_HOSTNAME
            value: {{ .Values.hostname | quote }}
          - name: IOB_K8S_REDIS_HOST
            value: {{ .Values.redis.host | quote }}
          - name: IOB_K8S_REDIS_PORT
            value: "{{ .Values.redis.port }}"
          - name: IOB_K8S_REDIS_PASSWORD
            value: {{ .Values.redis.password | quote }}
          - name: IOB_K8S_REDIS_DB
            value: "{{ .Values.redis.db }}"